### ISSUE TITLE
Nosmall system

### ISSUE THREAD

**Issue by Worldie1** [Fizo55/NosMall#2]
Nosmall credits will be managed in the account table

The character selection page will only display characters with a state == 1

- [x] Nosmall login front end

- [x] Nosmall login back end

- [x] Personnage selection front-end

- [x] Personnage selection back-end

- [x] Nosmall categories front end

- [x] Nosmall categories back end

- [x] nosmall_categories table

- [x] nosmall_shop_items table

**Comment by Fizo55** [comment]
All it's done. Now I need to code the send item function.
